name: Test

on:
  pull_request:

env:
  IMAGES_HOSTNAME: "*"

jobs:
  next-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: next/yarn.lock

      - name: Install eslint (for easier rebasing, could be added to packages.json later)
        working-directory: ./next
        run: yarn add --dev typescript eslint-config-next 'eslint@^9'

      - name: Install dependencies
        working-directory: ./next
        run: yarn install --frozen-lockfile

      - name: Running linter
        working-directory: ./next
        run: yarn run eslint --output-file ../next-eslint_report.json --format json
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          report-json: "next-eslint_report.json"
          only-pr-files: false
        continue-on-error: true
